version: "3.9"
services:
  neo4j-db:
    image: neo4j:4.2-enterprise
    restart: always
    command: /mnt/amos/load-dump.sh
    ports:
      - 7474:7474
      - 7687:7687
    working_dir: /mnt/amos
    volumes:
      - ./database/mount:/mnt/amos
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - DB_PASSWORD=amos
      - DB_PATH=/mnt/amos/dumps/testing-dump.dump
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
      - NEO4J_apoc_import_file_enabled=true
  kmap.backend:
    image: kmap.backend
    restart: always
    expose:
      - "8080"
    environment:
      NEO4J_HOST: localhost
      NEO4J_PORT: 7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: amos
      NEO4J_DATABASE: neo4j
    networks:
      - kmap-network
  kmap.frontend:
    image: kmap.frontend
    restart: always
    ports:
      - 8000:80
    networks:
      - kmap-network
networks:
  kmap-network:
