name: Backend build mac
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    env:
      working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile --prefer-offline --network-timeout 1000000
        working-directory: ${{ env.working-directory }}
      - run: yarn run build
        working-directory: ${{ env.working-directory }}
