name: Frontend unit tests
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [10.x, 12.x, 14.x, 15.x]
        browser: [chrome, firefox]
        include:
          - os: windows-latest
            node-version: 10.x
            browser: edge
          - os: windows-latest
            node-version: 12.x
            browser: edge
          - os: windows-latest
            node-version: 14.x
            browser: edge           
          - os: windows-latest
            node-version: 15.x
            browser: edge
    env:
      working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with: 
          command: yarn cypress run-ct
          browser: ${{ matrix.browser }}
          working-directory: ${{ env.working-directory }}
